src/TheWorld2/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld2.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(4096,MinimumLength =10)]
        public string Message { get; set; }
    }
}

src/TheWorld2/Controllers/Web/AppController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using TheWorld2.Services;
using TheWorld2.ViewModels;

namespace TheWorld2.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;

        public AppController(IMailService mailService, IConfigurationRoot config)
        {
            _mailService = mailService;
            _config = config;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.Contains("aol.com")) ModelState.AddModelError("","We do not support AOL addresses!");
            if (ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From TheWorld", model.Message);

                ModelState.Clear();

                ViewBag.UserMessage = "Message Sent";
            }

            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

src/TheWorld2/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}
<h2>About Me</h2>

src/TheWorld2/Views/App/Contact.cshtml
@model TheWorld2.ViewModels.ContactViewModel
@{ 
    ViewBag.Title = "Contact Page";
}

@section scripts {
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
 }
<h2>Contact Me</h2>
<form method="post">
    <div asp-validation-summary="ModelOnly"></div>
    @if (ViewBag.UserMessage != null)
    {
        <div>@ViewBag.UserMessage</div>
    }
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>
    <label>Email</label>
    <input type="email" asp-for="Email" />
    <span asp-validation-for="Email"></span>
    <label asp-for="Message"></label>
    <textarea cols="40" rows="4" asp-for="Message"></textarea>
    <span asp-validation-for="Message"></span>
    <div> <input type="submit" value="Send Message" /></div>
</form>

src/TheWorld2/Views/App/Index.cshtml
@{ 
    ViewBag.Title = "Home Page";
}
<h3>The World</h3>
<p>This will be a fun website soon!</p>

<div class="row">

    <div class="col-md-6 col-xs-8">
        <form>
            <div>
                <label>Date</label>
                <input />
            </div>
            <div>
                <label>Location</label>
                <input />
            </div>
            <div>
                <input type="submit" value="Add" />
            </div>
        </form>
    </div>
    <div class="col-md-6 col-xs-4">
        <h2>The Map</h2>
    </div>
</div>

src/TheWorld2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <div id="sidebar">
        <img src="~/img/user1.jpg" alt="headshot" class="headshot" />
        <span id="username">Sam Hastings</span>
        <ul class="nav">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        </ul>
    </div>
    <div id="wrapper">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button id="sidebarToggle" class="btn btn-primary">
                            <i class="fa fa-angle-left"></i>
                        </button>
                    </li>
                </ul>
                <a asp-controller="App" asp-action="Index" class="navbar-brand">The World</a>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-save"></i>Save
                        </a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-print"></i>Print
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="main" class="container-fluid">


            @RenderBody()
        </div>
        <div id="footer" class="container-fluid">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <h4 class="text-center text-info">&copy; 2017 The World Ltd.</h4>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>

    @RenderSection("scripts", false)
</body>
</html>